### ISSUE TITLE
Edit dropdown styling 

### ISSUE THREAD

**Issue by jcorkill** [neilerdwien/homepage-2017#34]
* Too much space at the top of the menu
* Hovers and underlines don't include the entire link
* The See all could use the carrot at the end > so that it helps it stand out as the link leading to more.
* In general the boxes seem wider than necessary, like they have extra space on the right side?
* And I'd suggest a tinge less padding/margin on the left of the words
* And if I'm getting *really* picky, I wish the box sat a couple of pixels lower on the menu bar, so the purple sits on the transition line.

**Comment by neilerdwien** [comment]
- Too much space at the top of the menu
Fixed.

- Hovers and underlines don't include the entire link
I don't know what you mean by this.

- The See all could use the carrot at the end > so that it helps it stand out as the link leading to more.
Added.

- In general the boxes seem wider than necessary, like they have extra space on the right side?
5em padding-right changed to 1em.

- And I'd suggest a tinge less padding/margin on the left of the words
1em changed to 0.8em.

- And if I'm getting really picky, I wish the box sat a couple of pixels lower on the menu bar, so the purple sits on the transition line.
Done.  

In the mockup, is the thin gray line above the megabanner intentional?

**Comment by neilerdwien** [comment]
Decrease leading.  Move to left.

**Comment by neilerdwien** [comment]
Leading changed from 0.8em to 0.6em.  Left padding changed from 0.8em to 0.5em.

Some change along the way made the purple bar above the dropdown menu too high.  I've lowered it so its bottom edge is on top of the image's top edge.
