### ISSUE TITLE
Reduce layer top space on Campuses and Instagram

### ISSUE THREAD

**Issue by jcorkill** [neilerdwien/homepage-2017#38]
The other layers look pretty evenly spaced, but Campuses and Instagram layers look like there's extra space at the top?

**Comment by neilerdwien** [comment]
Undoubtedly because because those layers have headings on the layer itself rather than inside a cell like "News" and "Events".  Should be easy to adjust.

**Comment by neilerdwien** [comment]
Try it now.  Not an exact match, but looks good to me.  I had to use negative margin to get the header higher, but long gone are the days when negative margin wasn't implemented in all browsers.

There is more space below #CaptureKState above the images.  But that is because there is space added above the images by the image grid itself.  Since we're not going to be using exactly that image grid, there is no reason to adjust it.

**Comment by jcorkill** [comment]
Definitely improved.

**Comment by neilerdwien** [comment]
In switching to Myriad Pro, I've done a lot of font and adjustment.  I think the vertical spacing here is OK.
