### ISSUE TITLE
Menu on wide displays, but smaller than 1200px 

### ISSUE THREAD

**Issue by neilerdwien** [neilerdwien/homepage-2017#62]
I predict this will be our most vexing issue...  The menu is designed to be 1200px wide.  On a wide window, say 1100px wide, the menu formats as 1200px and creates a horizontal scrollbar.

What should the menu look like on <1200px displays?  Reduce the font?  Remove the small Alumni-Athletics-Give links?  I'd suggest stacking them vertically, but I don't think that is possible in the Bootstrap framework.

I've seen some sites that show as many items as they can, and if there are more, they are replaced with a "..." indicator that opens to show the extra items.  I'm not sure this is possible in the Bootstrap framework either.

I think the Bootstrap solution is to change to the hamburger menu if the full menu doesn't fit.  But doing that on an 1100px window seems like overkill.  I have seen some sites that do use the hamburger on wider windows than I expected.

**Comment by jcorkill** [comment]
I think what you're describing is affecting Donna -- she doesn't typically keep her window open quite as wide as the new homepage requires. I had her look at UConn for comparison and UConn's header and menus slides in from the right and everything else gets smaller until it has to be a hamburger menu. Of course, their menu isn't as wide as ours is... so that helps. I do really like the header -- magnifying glass and A-Z -- moving in from the right though.

**Comment by jcorkill** [comment]
It does have me wondering if our main tab text is a little big...

**Comment by neilerdwien** [comment]
This is a duplicate issue -- fixed too!
